project 'MBProgressHUD+XL.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MBProgressHUD+XL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MBProgressHUD+XL
  
  pod 'MBProgressHUD', '~> 1.1.0'
  
  target 'MBProgressHUD+XLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MBProgressHUD+XLUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
